image: Visual Studio 2015
configuration:
- Debug
- DebugDLL
- DebugDLL_fixed
- Release
- ReleaseDLL
- ReleaseDLL_fixed

platform:
- Win32
- x64

build:
  project: win32\VS2015\opus.sln
  parallel: true
  verbosity: minimal

after_build:
- cmd: >-
    mkdir %APPVEYOR_BUILD_FOLDER%\artifacts

    cd %APPVEYOR_BUILD_FOLDER%\win32\VS2015\%PLATFORM%\%CONFIGURATION%

    for %%a in (lib dll exp pdb) do if exist opus.%%a copy opus.%%a %APPVEYOR_BUILD_FOLDER%\artifacts\

    cd %APPVEYOR_BUILD_FOLDER%

    7z a opus.zip .\artifacts\* include\*.h

test_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%\win32\VS2015\%PLATFORM%\%CONFIGURATION%

    test_opus_api.exe

    test_opus_decode.exe

    test_opus_encode.exe

artifacts:
- path: opus.zip
